### ISSUE TITLE
not working on python3 64 bits?

### ISSUE THREAD

**Issue by lenLRX** [Keithenneu/dota2comm#3]
I am testing interactiveConsole on win10 64bit python3.5.2-64bit and on Dota2-64bits.

I compiled the code on vs2015 and x64 config, and it fails
then i compiled with win32 config and it works

**Comment by Keithenneu** [comment]
It should be independant of the pathon version/32-64-thingy.
The dota2 and c++ ones are the ones causing issues.
How does it fail exactly?
