### ISSUE TITLE
Use case

### ISSUE THREAD

**Issue by elpaxdota** [Keithenneu/dota2comm#5]
I recently saw your project. It's some great stuff. But I don't know where to use this :) I mean I know what your project is. It can "control" bots in real time from outside the dota client. And I'm so confused :) I want to use this interesting project but can find use cases :) Its strange. Can you write some use cases ?

**Comment by Keithenneu** [comment]
It's not necessarily about controlling bots. It's about communicating with them.
It's purpose is to help with development. For example for debugging, machine learning, stuff like that.
I doubt there are any usefull use cases for this project alone. It's just a helper for other projects.
