### ISSUE TITLE
Real player and node client

### ISSUE THREAD

**Issue by elpaxdota** [Keithenneu/dota2comm#6]
Sorry but I have one more question. I can find answers by myself but it will take lot of time.
1. Can this "project" control/communicate with real player in normal match ? or only bots in local lobby.
2. There is few projects like this https://github.com/Arcana/node-dota2. That can "emulate" dota client. (work with GC messages). Can your project (with some rewriting maybe) somehow work with emulated client in Node environment or it needed full normal client ?

**Comment by Keithenneu** [comment]
1. Bots and local lobby only. (The Lua runs on the server, not the client side)
2. As I said in (1), it communicates with the servers Lua code. If you wan't to communicate with the custom client, rewrite the custom client.
